# -*- coding: utf-8 -*-
"""Tikiproject_week1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vXOootMNmZuJYqdbVdOuoJMMcqrxJnk1
"""

import requests
import re
import json

# request page may pha ca phe
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36'}
r = requests.get('https://tiki.vn/may-pha-ca-phe/c1939?src=c.1882.hamburger_menu_fly_out_banner', headers=headers)
print(r.text[:1000])

# parse html into beautiful soup
from bs4 import BeautifulSoup

soup = BeautifulSoup(r.text, 'html.parser')

print(soup.prettify()[:100])

print("\nAll occurences of the product div sections:")
products = soup.find_all('a', {'class':'product-item'})
print("Type:", type(products))
print("Number of products:", len(products))

scripts = soup.find_all('script', {'type': 'application/ld+json'})
test = scripts[1] 
print(test)

# pattern = r'.*"sku":"(\d+)".*'
# print(pattern)
# sku = re.search(pattern, scripts[0].text)
# script_element = test.text.split(',')
# for i in script_element :
    # print(i)
# print(script_element)
# print(script_element)

# find product_id
pattern = r'.*"sku":"(\d+)".*'
sku = re.findall(pattern, test.text)
print(product_id)

# file title
pattern = r'"name":"(.*)","des'
title = re.findall(pattern, test.text)
print(title)

# find price
pattern = r'"price":(\d+)}'
price = re.findall(pattern, test.text)
print(price)

# find image
pattern = r'"image":"(.*\.jpg)"'
image = re.findall(pattern, test.text)
print(image)