# -*- coding: utf-8 -*-
"""Tikiproject_week1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vXOootMNmZuJYqdbVdOuoJMMcqrxJnk1
"""

import requests
import re
import json

# request page may pha ca phe
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36'}

r = requests.get('https://tiki.vn/may-pha-ca-phe/c1939?page=1&src=c.1882.hamburger_menu_fly_out_banner', headers=headers)

# parse html into beautiful soup
from bs4 import BeautifulSoup

soup = BeautifulSoup(r.text, 'html.parser')

print(soup.prettify()[:100])

# identify number of item
print("\nAll occurences of the product div sections:")
products = soup.find_all('a', {'class':'product-item'})
print("Type:", type(products))
print("Number of products:", len(products))

# scripts of all item in page 1
scripts = soup.find_all('script', {'type': 'application/ld+json'})
data = []
for i in range(1,len(products)+1): 
  test = scripts[i]
  # find product_id
  pattern = r'.*"sku":"(\d+)".*'
  product_id1 = str(re.findall(pattern, test.text)).strip('[')
  product_id2 = product_id1.strip(']')
  product_id = product_id2.strip("'")
 
  # file title
  pattern = r'"name":"(.*)","des'
  title1 = str(re.findall(pattern, test.text)).strip('[')
  title2 = title1.strip(']')
  title = title2.strip("'")
  
  # find price
  pattern = r'"price":(\d+)}'
  price1 = str(re.findall(pattern, test.text)).strip('[')
  price2 = price1.strip(']')
  price = price2.strip("'")
  
  # find image
  pattern = r'"image":"(.*g)","name'
  image_url1 = str(re.findall(pattern, test.text)).strip('[')
  image_url2 = image_url1.strip(']')
  image_url = image_url2.strip("'")
  
  # create data contain dict of 48 items
  
  d_script = {'product_id':'', 'title':'', 'price':'', 'image_url':''}
  try:
    d_script['product_id'] = product_id
    d_script['title'] = title
    d_script['price'] = price
    d_script['image_url'] = image_url
    data.append(d_script)
    
  except:
    print("We got one article error!")

# create dataframe
import pandas as pd
 
product = pd.DataFrame(data = data)

product